services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
      - ./to_restore:/to_restore
    restart: always  
  frontend:
    image: forsythcreations/mde:frontend-latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - postgres
    restart: always
  backend:
    image: forsythcreations/mde:backend-latest
    volumes:
      - ./backend/app:/backend/app
    environment:
      - PYTHONUNBUFFERED=1
      # - MONGO_URI=mongodb://padua:password@mymongo:27017
      - HOST=0.0.0.0
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - frontend
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 # 10 minutes
    restart: unless-stopped